### ISSUE TITLE
template嵌套时格式化出错

### ISSUE THREAD

**Issue by peterchealse** [webdzq/plugins#2]
```
<template>
  <template>
  </template>
</template>
```
这种情况格式化出错

**Comment by webdzq** [comment]
应该不会的。你可以参考这个项目：
https://github.com/webdzq/wx-wpy-demo/blob/master/wxxcxtask_v1.0__2017_07-31/src/pages/reviewWork/reviewWork.wpy

**Comment by webdzq** [comment]
<template>
  <import src="../../components/question/question.wxml" />
  ...
          <template is="question" data="{{question: question.questions, display: 'simple'}}">
          </template>
...
</template>
